// Generated by https://quicktype.io

export interface RegisterData {
    name:         string;
    phone_number: string;
    email:        string;
    password:     string;
    role:         string;
}
